In [6]:
pip install pymongo

Requirement already satisfied: pymongo in /usr/local/lib/python3.12/dist-packages (4.17.0)
Requirement already satisfied: dnspython<3.0.0,>=2.6.1 in /usr/local/lib/python3.12/dist-packages (from pymongo) (2.8.0)

In [7]:
import pandas as pd
import pymongo
df=pd.read_csv('/content/data.csv')
df.head()

,id,Gender,Age,Driving_License,Region_Code,Previously_Insured,Vehicle_Age,Vehicle_Damage,Annual_Premium,Policy_Sales_Channel,Vintage,Response
0,1,Male,44,1,28.0,0,> 2 Years,Yes,40454.0,26.0,217,1
1,2,Male,76,1,3.0,0,1-2 Year,No,33536.0,26.0,183,0
2,3,Male,47,1,28.0,0,> 2 Years,Yes,38294.0,26.0,27,1
3,4,Male,21,1,11.0,1,< 1 Year,No,28619.0,152.0,203,0
4,5,Female,29,1,41.0,1,< 1 Year,No,27496.0,152.0,39,0

In [8]:
data=df.to_dict(orient='records')

In [ ]:
DB_NAME="proj-1"
COLLECTION_NAME="proj1-data"
CONNECTION_URL="mongodb+srv://roy172758_db_user:t05eQaZ6LehyqpKW@cluster0.1ipd1tr.mongodb.net/?appName=Cluster0"

In [10]:
client = pymongo.MongoClient(CONNECTION_URL)
data_base = client[DB_NAME]
collection = data_base[COLLECTION_NAME]

In [11]:
rec = collection.insert_many(data)

In [12]:
df = pd.DataFrame(list(collection.find()))
df.head(2)

,_id,id,Gender,Age,Driving_License,Region_Code,Previously_Insured,Vehicle_Age,Vehicle_Damage,Annual_Premium,Policy_Sales_Channel,Vintage,Response
0,6a774685fdf1aa737f04dc0e,1,Male,44,1,28.0,0,> 2 Years,Yes,40454.0,26.0,217,1
1,6a774685fdf1aa737f04dc0f,2,Male,76,1,3.0,0,1-2 Year,No,33536.0,26.0,183,0